apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: source-cluster-ca-cert
  namespace: kafka-target
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: kafka-source-store
    kind: SecretStore
  target:
    name: source-cluster-ca-cert
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: source-cluster-ca-cert
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: source-mirror-user
  namespace: kafka-target
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: kafka-source-store
    kind: SecretStore
  target:
    name: source-mirror-user
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: source-mirror-user
