apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-mirror
  namespace: argocd
spec:
  project: streamshub
  source:
    repoURL: https://github.com/streamshub/streamshub-gitops.git
    # TODO: switch back to HEAD before merge
    targetRevision: argocd-kafka-examples
    path: examples/scenarios/kafka-mirror
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: argocd
    syncOptions:
      - CreateNamespace=true
