apiVersion: v1
kind: Secret
metadata:
  name: gitea-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: git
  url: http://gitea-http.gitea.svc:3000/tutorial-user/streamshub-gitops.git
  username: tutorial-user
  password: tutorial-password
  insecure: "true"
