apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: streamshub-gitops
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          - name: strimzi-operator
            path: examples/operators/strimzi/overlays/kubernetes
            namespace: strimzi-operator
          - name: keycloak-operator
            path: examples/operators/keycloak/overlays/kubernetes
            namespace: keycloak
          - name: external-secrets-operator
            path: examples/operators/external-secrets/overlays/kubernetes
            namespace: external-secrets-operator
    - git:
        repoURL: https://github.com/streamshub/streamshub-gitops.git
        revision: HEAD
        directories:
          - path: examples/scenarios/*
  template:
    metadata:
      name: '{{ default .path.basename .name }}'
      labels:
        app.kubernetes.io/part-of: streamshub-gitops
    spec:
      project: streamshub
      source:
        repoURL: https://github.com/streamshub/streamshub-gitops.git
        targetRevision: HEAD
        path: '{{ default .path .path.path }}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ default "" .namespace }}'
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
        managedNamespaceMetadata:
          labels:
            argocd.argoproj.io/managed-by: argocd
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
