apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - database-secret.yaml
  - admin-secret.yaml
  - database.yaml
  - keycloak.yaml
  - realm-import.yaml
