apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: streams-for-kafka-operator
  namespace: streams-kafka-operator
spec:
  channel: amq-streams-3.2.x
  installPlanApproval: Automatic
  name: amq-streams
  source: redhat-operators
  sourceNamespace: openshift-marketplace
